### ISSUE TITLE
add new info to munis_df 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#50]
add new columns with:

- [x] full municipality name in Portuguese
- [x] x and y dimensions of figures saved in .png
- [ ] perhaps lat and lon coordinates to zoom in specific cities like Manaus, or Campo grande

**Comment by kauebraga** [comment]
I'll add to this:
- [ ] Identification whether the muni is included in the project as a metro region

**Comment by kauebraga** [comment]
My suggestion to including metro regions:
- Add a column to `munis_df` (like `metro_munis` ) identifying the municipalities associated with the muni. If there is no metro muni included, than it will contain only the muni code. Else, will contain the muni code and the other codes related to the metro region.

Suppose that Fortaleza's GTFS included metro munis 213 and 241. The value in column `metro_munis` for Fortaleza will be `2304400,213,241`.
If we want to extract these muni, instead of runnig `munis_df$code_muni`, we will run `unlist(strsplit(munis_df$metro_munis, ","))`, and we should be fine, or maybe a simple as a shortcurt with `year` as input.

**Comment by kauebraga** [comment]
Actually we would pass `munis_df$abrev_muni` to run the functions, but to extract the muni codes internally in the functions we would run `subset(munis_sf, abrev_muni == sigla_muni)$metro_munis %>% str_split(",") %>% unlist` instead of `subset(munis_sf, abrev_muni == sigla_muni)$code_muni`

**Comment by kauebraga** [comment]
map ratios and metro regions done at https://github.com/ipeaGIT/acesso_oport/commit/8134b7d8384afdbad30a6cd475a30dc08bc458a9

**Comment by rafapereirabr** [comment]
podemos fechar esse neh?
